services:
  y2y-api-db:
    image: postgres:17-alpine
    container_name: y2y-api.db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - y2y-api-db-data:/var/lib/postgresql/data
volumes:
  y2y-api-db-data:
